### ISSUE TITLE
Help 500 Internal server error

### ISSUE THREAD

**Issue by dudenk** [vuetifyjs/webpack-ssr#34] opened 2018-02-21 10:16 UTC
webpack built d41f63f5553d53fc63a7 in 6995ms
error during render : /
TypeError: Cannot read property 'split' of undefined
    at checkVueVersion (~/vuetify/es5/components/Vuetify/index.js:76:0)
    at Object.install (~/vuetify/es5/components/Vuetify/index.js:35:0)
    at Function.Vue.use (/Users/gag/Dev/Vue/pojokbogor-ssr/node_modules/vue/dist/vue.runtime.common.js:4679:22)
    at Object.<anonymous> (assets/app.js:23:4)
    at __webpack_require__ (webpack:/webpack/bootstrap 327edda16b7b076ee411:25:0)
    at Object.<anonymous> (server-bundle.js:1617:63)
    at __webpack_require__ (webpack:/webpack/bootstrap 327edda16b7b076ee411:25:0)
    at module.exports.module.exports.list (webpack:/webpack/bootstrap 327edda16b7b076ee411:93:0)
    at Object.<anonymous> (server-bundle.js:98:10)
    at evaluateModule (/Users/gag/Dev/Vue/pojokbogor-ssr/node_modules/vue-server-renderer/build.js:8155:21)

how to fix it.

**Comment by KaelWD** [comment] 2018-02-21 13:46
Duplicate of vuetifyjs/webpack#5

**Closed by KaelWD** 2018-02-21 13:46 UTC

**Comment by ArnyS** [comment] 2018-02-22 13:51
what file to change?
